### ISSUE TITLE
Announce current version to all users

### ISSUE THREAD

**Issue by guising** [openfoodsource/OFS_federation#25]
Make announcement to all OFS users that a new version is available, in part to keep them up to date, and in part to help identify bugs to fix for subsequent releases.

**Comment by ayoungethan** [comment]
is this announcement completed with your New Year's letter?

**Comment by guising** [comment]
Yes. Seems this will be accomplished as soon as I send that out (got delayed). Will close when done.

**Comment by guising** [comment]
Support letter sent to current user groups, so this is effectively completed.
