### ISSUE TITLE
member discount on customer receipt

### ISSUE THREAD

**Issue by ayoungethan** [openfoodsource/OFS_federation#28]
does (or can) OFS create customer receipts or invoices that state, "You saved $xxx as a member" OR (for non-members) "become a member and save $xxx on orders like this in the future"

Purpose:  advertise / reinforce membership options and loyal customer base

**Comment by guising** [comment]
Member (and producer) invoices are fully customizable. Anything that can be calculated with the available numbers can be included. The specific data of this question might need some additional variable exposure (such as membership type) which might not currently be available, but would be fairly simple to include. Or, if it only depends on an already exposed value (like customer markup), then some configuration of the template will take care of it.
