### ISSUE TITLE
Create OFS software download/registration process via OFS.org

### ISSUE THREAD

**Issue by ayoungethan** [openfoodsource/OFS_federation#8]
Someone must at minimum enter their (or their organization's) contact information and agree to subscribe to the OFS_users mailing list in order gain access to the OFS software package download.

This helps us understand who is interested in the software, and why.

**Comment by ayoungethan** [comment]
Maybe this could include a short optional survey that asks how they intend to use the software, giving them a few options, such as:  1. i don’t know yet 2. i’m confused by these options 3. on our own server 4. i need a hosting or server, i guess; and also what CMS?  Drupal, Joomla, Wordpress, none, other?

**Comment by ayoungethan** [comment]
@guising created a first process.  We are working on an automated emailer

**Comment by guising** [comment]
Here is a free plugin option: https://wordpress.org/plugins/new-user-email-set-up/installation/

**Comment by guising** [comment]
On the other hand, I wonder if a non-automated email would be more "personal" and generate better rapport. Unles the volume is terribly high, it shouldn't be too much trouble.

**Comment by ayoungethan** [comment]
I'm marking this as closed since we have a personalized process that seems to wrok for the time-being.  I think any further automation should reopen as a new issue?
